---
lib_name: lib_i2c
project: '{{lib_name}}'
title: '{{lib_name}}: XMOS I2C Library'
version: 6.2.0

documentation:
  exclude_patterns_path: doc/exclude_patterns.inc
  substitutions_path: doc/substitutions.inc
  root_doc: doc/rst/index.rst
  linkcheck_ignore_regex: ['']
  doxygen_projects:
    lib_i2c:
      doxyfile_path: doc/Doxyfile.inc
  pdfs:
    doc/rst/index.rst:
      pdf_title: '{{title}}'
      pdf_filename: '{{lib_name}}_v{{version}}'
    README.rst:
      pdf_title: '{{title}} (README)'
      pdf_filename: '{{lib_name}}_v{{version}}_readme'
      pdf_short: yes
